// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcBasePremiumCpp
DataFrame calcBasePremiumCpp(DataFrame df, double age_base, double age_factor, double bmi_base, double bmi_factor, double smoker_penalty, double arthritis_factor, double diabetes_factor, double heart_disease_factor, double asthma_factor, double hypertension_factor, double none_factor);
RcppExport SEXP _insurePriceR_calcBasePremiumCpp(SEXP dfSEXP, SEXP age_baseSEXP, SEXP age_factorSEXP, SEXP bmi_baseSEXP, SEXP bmi_factorSEXP, SEXP smoker_penaltySEXP, SEXP arthritis_factorSEXP, SEXP diabetes_factorSEXP, SEXP heart_disease_factorSEXP, SEXP asthma_factorSEXP, SEXP hypertension_factorSEXP, SEXP none_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type age_base(age_baseSEXP);
    Rcpp::traits::input_parameter< double >::type age_factor(age_factorSEXP);
    Rcpp::traits::input_parameter< double >::type bmi_base(bmi_baseSEXP);
    Rcpp::traits::input_parameter< double >::type bmi_factor(bmi_factorSEXP);
    Rcpp::traits::input_parameter< double >::type smoker_penalty(smoker_penaltySEXP);
    Rcpp::traits::input_parameter< double >::type arthritis_factor(arthritis_factorSEXP);
    Rcpp::traits::input_parameter< double >::type diabetes_factor(diabetes_factorSEXP);
    Rcpp::traits::input_parameter< double >::type heart_disease_factor(heart_disease_factorSEXP);
    Rcpp::traits::input_parameter< double >::type asthma_factor(asthma_factorSEXP);
    Rcpp::traits::input_parameter< double >::type hypertension_factor(hypertension_factorSEXP);
    Rcpp::traits::input_parameter< double >::type none_factor(none_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(calcBasePremiumCpp(df, age_base, age_factor, bmi_base, bmi_factor, smoker_penalty, arthritis_factor, diabetes_factor, heart_disease_factor, asthma_factor, hypertension_factor, none_factor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_insurePriceR_calcBasePremiumCpp", (DL_FUNC) &_insurePriceR_calcBasePremiumCpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_insurePriceR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
