# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname calcBasePremiumCpp
calcBasePremiumCpp <- function(df, age_base, age_factor, bmi_base, bmi_factor, smoker_penalty, arthritis_factor = 0.0, diabetes_factor = 0.0, heart_disease_factor = 0.0, asthma_factor = 0.0, hypertension_factor = 0.0, none_factor = 0.0) {
    .Call(`_insurePriceR_calcBasePremiumCpp`, df, age_base, age_factor, bmi_base, bmi_factor, smoker_penalty, arthritis_factor, diabetes_factor, heart_disease_factor, asthma_factor, hypertension_factor, none_factor)
}

